### ISSUE TITLE
test to check events times always precede build times

### ISSUE THREAD

**Issue by wjchulme** [opensafely/database-notebooks#34] opened 2022-04-12 20:08 UTC
From @HelenCEBM on [slack](https://bennettoxford.slack.com/archives/C010SJ89SA3/p1649407660291229?thread_ts=1649342374.590889&cid=C010SJ89SA3);

> is it worth building in a warning if the latest data in a dataset is later than the build date to prompt us to re-run before releasing?

This follows a notebook update that was run before the weekly database build had fully finished.

**Comment by iaindillingham** [comment] 2023-05-04 12:04
I'm going to close this issue with this comment. Whilst it would be nice to check the run date is after the most recent build date, that would add extra complexity to each report for what is, hopefully, an edge case. At some point, I think we'd like to make the generation of these reports dependent on a successful build, which would mean the issue is addressed by the orchestration of each report, rather than within each report.

**Closed by iaindillingham** 2023-05-04 12:04 UTC
